/*
Single LED Blinky!
https://www.clevertronics.blogspot.com
Used Hardware : STM32F030F4 Barebones
Used IDE : STM CUBE IDE with CUBE-MX 
*/
/*
User code inside while loop is given here. Rest of the sections are generated by IDE in default.
Select "PIN 1" as "GPIO_OUT" in "PORT A" of STM32F030F4 via graphical selection interphase before genearting code.
*/


int main(void)
{
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  
  while (1)
  {
	  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_SET);  //LED ON
	  HAL_Delay(100);
     
	  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_RESET);  //LED OFF
	  HAL_Delay(100);
  }
}
