/*
R G B LED Blinky with Scroll pattern!
https://www.clevertronics.blogspot.com
Used Hardware : STM32F030F4 Barebones
Used IDE : STM CUBE IDE with CUBE-MX 
*/
/*
User code inside while loop is given here. Rest of the sections are generated by IDE in default.
Select "PIN 0,1,2" respectively as "GPIO_OUT" in "PORT A" of STM32F030F4 via graphical selection interphase before genearting code.
*/

/*USER code decleration*/
 
 while (1)
  {
     HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_0);  // Port A of GPIO is used at PIN 0.
     HAL_Delay(200);                         //200ms delay.
     
     HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_1);  // Port A of GPIO is used at PIN 1.
	   HAL_Delay(400);                         //400ms delay.

     HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_2);  // Port A of GPIO is used at PIN 2.
	   HAL_Delay(600);                         //600ms delay.
   }
