/*
Pushbutton LED Toggling!
https://www.clevertronics.blogspot.com
Used Hardware : STM32F030F4 Barebones
Used IDE : STM CUBE IDE with CUBE-MX 
*/
/*
User code inside while loop is given here. Rest of the sections are generated by IDE in default.
Select "PIN 0,1" respectively as "GPIO_OUT and GPLO_IN" in "PORT A" of STM32F030F4 via graphical selection interphase before genearting code.
Connect Toggle SWITCH to PIN 0.
*/

/*USER code decleration*/

if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0))                         //Read GPIO 0
   {
	      HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_SET);      // switch on LED1
	 }
	   else
	 {
	     HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_RESET);    // switch off LED1
	 }
